/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.airpot.airport.t1poo.UI;

import javax.swing.ImageIcon;
import com.airpot.airport.t1poo.entidades.TipoDocumento;
import com.airpot.airport.t1poo.gestion.PasajeroGestionDAO;
import com.airpot.airport.t1poo.gestion.TipoDocumentoGestionDAO;
import com.airpot.airport.t1poo.entidades.Pasajero;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RIPCONCIV
 */
public class MantenimientoPasajero extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoPasajero.class.getName());
    TipoDocumentoGestionDAO tipoDocumentosDAO = new TipoDocumentoGestionDAO();
    PasajeroGestionDAO pasajeroDAO = new PasajeroGestionDAO();
    /**
     * Creates new form MantenimientoPasajero
     */
    public MantenimientoPasajero() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/avion.png")).getImage());
        cargarTipoDocumento();
        cargarTablaPasajeros();
        txtIdPasajero.setVisible(false);
    }
    private void cargarTipoDocumento() {
    cboTipoDocumento.removeAllItems();


    for (TipoDocumento m : tipoDocumentosDAO.listarTipoDocumentos()) {
        cboTipoDocumento.addItem(m);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPasajeros = new javax.swing.JTable();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboTipoDocumento = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        txtIdPasajero = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Pasajeros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        tablaPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPasajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPasajerosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPasajeros);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 570, 320));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, 40));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 40));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("Telefono");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setText("TipoDocumento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        cboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>());
        jPanel1.add(cboTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        txtIdPasajero.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIdPasajero.setFocusable(false);
        jPanel1.add(txtIdPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 30, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int id = Integer.parseInt(txtIdPasajero.getText().trim());
        String nombre = txtNombre.getText().trim();
        String documento = txtDocumento.getText().trim();
        String telefono = txtTelefono.getText().trim();
        TipoDocumento tpdoc = (TipoDocumento) cboTipoDocumento.getSelectedItem();
        int idTipoDocumento = tpdoc.getIdtipodocumento();
        if(id==0){
            // 2. Validaciones
    if (nombre.isEmpty() || documento.isEmpty() || telefono.isEmpty() || idTipoDocumento == 0) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos.");
        return;
    }

    // 3. Crear objeto pasajero
        Pasajero p = new Pasajero();
        p.setNombre(nombre);
        p.setDocumento(documento);
        p.setTelefono(telefono);
        p.setIdtipodocumento(idTipoDocumento);

    // 4. Llamar al DAO para guardar
        int ok = pasajeroDAO.registrar(p);

    // 5. Resultado
        if (ok!=0) {
        JOptionPane.showMessageDialog(this, "Pasajero registrado correctamente.");
        //cargarTablaPasajeros(); // refresca la tabla si ya la tienes
        limpiarCampos();        // limpia los campos
        } else {
        JOptionPane.showMessageDialog(this, "Error al guardar pasajero.");
        }
        cargarTablaPasajeros();
        }
        else {
                // 2. Validaciones
    if (nombre.isEmpty() || documento.isEmpty() || telefono.isEmpty() || idTipoDocumento == 0) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos.");
        return;
    }

    // 3. Crear objeto pasajero
        Pasajero p = new Pasajero();
        p.setIdpasajero(id);
        p.setNombre(nombre);
        p.setDocumento(documento);
        p.setTelefono(telefono);
        p.setIdtipodocumento(idTipoDocumento);

    // 4. Llamar al DAO para guardar
        int ok = pasajeroDAO.actualizar(p);

    // 5. Resultado
        if (ok!=0) {
        JOptionPane.showMessageDialog(this, "Pasajero actualizado correctamente.");
        //cargarTablaPasajeros(); // refresca la tabla si ya la tienes
        limpiarCampos();        // limpia los campos
        } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar pasajero.");
        }
        cargarTablaPasajeros();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaPasajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPasajerosMouseClicked
      int fila = tablaPasajeros.getSelectedRow();
        if (fila >= 0) {
            txtIdPasajero.setText(tablaPasajeros.getValueAt(fila, 0).toString());
            txtNombre.setText(tablaPasajeros.getValueAt(fila, 1).toString());
            txtDocumento.setText(tablaPasajeros.getValueAt(fila, 2).toString());
            txtTelefono.setText(tablaPasajeros.getValueAt(fila, 3).toString());
            cboTipoDocumento.setSelectedIndex(
                    Integer.parseInt(tablaPasajeros.getValueAt(fila, 4).toString())-1
                    );
        }
    }//GEN-LAST:event_tablaPasajerosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(txtIdPasajero.getText().trim());
         if (id==0){
             JOptionPane.showMessageDialog(this, "Seleccione un pasajero");
         } else {
             int opcion=JOptionPane.showConfirmDialog(null, "¿Desea eliminar a este pasajero?", "Confirmación", JOptionPane.YES_NO_OPTION,  JOptionPane.QUESTION_MESSAGE);
             if (opcion==JOptionPane.YES_OPTION){
                pasajeroDAO.eliminar(id);
                JOptionPane.showMessageDialog(this, "Pasajero eliminado correctamente.");
                cargarTablaPasajeros();
                limpiarCampos();
             }
             
         }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private void limpiarCampos() {
    txtIdPasajero.setText("0");
    txtNombre.setText("");
    txtDocumento.setText("");
    txtTelefono.setText("");
    cboTipoDocumento.setSelectedIndex(0);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoPasajero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<TipoDocumento> cboTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaPasajeros;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtIdPasajero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

   public void cargarTablaPasajeros() {

    String columnas[] = {"ID", "Nombre", "Documento", "Teléfono","idtipodocumento"};
       DefaultTableModel modelo = new DefaultTableModel(null, columnas);

       ArrayList<Pasajero> lista = pasajeroDAO.listarPasajeros();

    for (Pasajero p : lista) {
        Object fila[] = {
            p.getIdpasajero(),
            p.getNombre(),
            p.getDocumento(),
            p.getTelefono(),
            p.getIdtipodocumento()
        };
        modelo.addRow(fila);
    }

    tablaPasajeros.setModel(modelo);
} 
}
