/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.airpot.airport.t1poo.UI;

import javax.swing.ImageIcon;
import com.airpot.airport.t1poo.entidades.TipoDocumento;
import com.airpot.airport.t1poo.gestion.VueloGestionDAO;
import com.airpot.airport.t1poo.gestion.PuertaGestionDAO;
import com.airpot.airport.t1poo.entidades.Vuelo;
import com.airpot.airport.t1poo.entidades.Puerta;
import com.airpot.airport.t1poo.entidades.VueloListado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RIPCONCIV
 */
public class MantenimientoVuelo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoVuelo.class.getName());
    
    private VueloGestionDAO vueloDAO = new VueloGestionDAO();
    private PuertaGestionDAO puertaDAO = new PuertaGestionDAO();
    /**
     * Creates new form MantenimientoPasajero
     */
    public MantenimientoVuelo() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/avion.png")).getImage());
        cargarPuerta();
        cargarTablaVuelo();
        txtIdVuelo.setVisible(false);
        this.setResizable(false);
    }
     private void cargarPuerta() {
      cboPuerta.removeAllItems();
        for (Puerta m : puertaDAO.listarPuerta()) {
            cboPuerta.addItem(m);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtDestino = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        txtOcupado = new javax.swing.JTextField();
        txtOrigen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboPuerta = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        txtIdVuelo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        txtCapacidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Vuelo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar_1.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVuelosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVuelos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 570, 430));
        jPanel1.add(txtOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 140, 40));
        jPanel1.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 40));

        jLabel1.setText("Origen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Destino");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("Capacidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setText("Ocupados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        cboPuerta.setModel(new javax.swing.DefaultComboBoxModel<>());
        jPanel1.add(cboPuerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        txtIdVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIdVuelo.setFocusable(false);
        jPanel1.add(txtIdVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 30, -1));
        jPanel1.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, 40));

        jLabel5.setText("Puerta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int id = Integer.parseInt(txtIdVuelo.getText().trim());
        String origen = txtOrigen.getText().trim();
        String destino = txtDestino.getText().trim();
        int capacidad = Integer.parseInt(txtCapacidad.getText().trim());
        int ocupado = Integer.parseInt(txtOcupado.getText().trim());
        Puerta puertacb = (Puerta) cboPuerta.getSelectedItem();
        int idpuerta = puertacb.getIdpuerta();
        if(id==0){
            // 2. Validaciones
    if (origen.isEmpty() || destino.isEmpty() || capacidad==0) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos.");
        return;
    }

    // 3. Crear objeto pasajero
        Vuelo p = new Vuelo();
        p.setOrigen(origen);
        p.setDestino(destino);
        p.setCapacidad(capacidad);
        p.setOcupados(ocupado);
        p.setIdpuerta(idpuerta);

    // 4. Llamar al DAO para guardar
        int ok = vueloDAO.registrar(p);

    // 5. Resultado
        if (ok!=0) {
        JOptionPane.showMessageDialog(this, "Vuelo registrado correctamente.");
        //cargarTablaPasajeros(); // refresca la tabla si ya la tienes
        limpiarCampos();        // limpia los campos
        } else {
        JOptionPane.showMessageDialog(this, "Error al guardar vuelo.");
        }
        cargarTablaVuelo();
        }
        else {
                // 2. Validaciones
    if (origen.isEmpty() || destino.isEmpty() || capacidad==0) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos.");
        return;
    }

    // 3. Crear objeto pasajero
         Vuelo p = new Vuelo();
        p.setOrigen(origen);
        p.setDestino(destino);
        p.setCapacidad(capacidad);
        p.setOcupados(ocupado);
        p.setIdpuerta(idpuerta);
        p.setIdvuelo(id);

    // 4. Llamar al DAO para guardar
        int ok = vueloDAO.actualizar(p);

    // 5. Resultado
        if (ok!=0) {
        JOptionPane.showMessageDialog(this, "Vuelo actualizado correctamente.");
        //cargarTablaPasajeros(); // refresca la tabla si ya la tienes
        limpiarCampos();        // limpia los campos
        } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar al vuelo.");
        }
        cargarTablaVuelo();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVuelosMouseClicked
      int fila = tablaVuelos.getSelectedRow();
        if (fila >= 0) {
            int id = Integer.parseInt(tablaVuelos.getValueAt(fila, 0).toString());
            Vuelo vuelo=vueloDAO.buscarVuelo(id);
            txtIdVuelo.setText(String.valueOf(vuelo.getIdvuelo()));
            txtOrigen.setText(vuelo.getOrigen());
            txtDestino.setText(vuelo.getDestino());
            txtCapacidad.setText(String.valueOf(vuelo.getCapacidad()));
            txtOcupado.setText(String.valueOf(vuelo.getOcupados()));
            cboPuerta.setSelectedIndex(
                    vuelo.getIdpuerta()-1
                    );
        }
    }//GEN-LAST:event_tablaVuelosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(txtIdVuelo.getText().trim());
         if (id==0){
             JOptionPane.showMessageDialog(this, "Seleccione un vuelo");
         } else {
             int opcion=JOptionPane.showConfirmDialog(null, "¿Desea eliminar este vuelo?", "Confirmación", JOptionPane.YES_NO_OPTION,  JOptionPane.QUESTION_MESSAGE);
             if (opcion==JOptionPane.YES_OPTION){
                vueloDAO.eliminar(id);
                JOptionPane.showMessageDialog(this, "vuelo eliminado correctamente.");
                cargarTablaVuelo();
                limpiarCampos();
             }
             
         }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private void limpiarCampos() {
    txtIdVuelo.setText("0");
    txtOrigen.setText("");
    txtDestino.setText("");
    txtOcupado.setText("");
    cboPuerta.setSelectedIndex(0);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoVuelo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Puerta> cboPuerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaVuelos;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtIdVuelo;
    private javax.swing.JTextField txtOcupado;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables

 public void cargarTablaVuelo() {

    String columnas[] = {"ID", "Origen","Destino" ,"Capacidad", "Ocupados","Puerta"};
       DefaultTableModel modelo = new DefaultTableModel(null, columnas);

       ArrayList<VueloListado> lista = vueloDAO.listarVuelos2();

    for (VueloListado p : lista) {
        Object fila[] = {
            p.getIdvuelo(),
            p.getOrigen(),
            p.getDestino(),
            p.getCapacidad(),
            p.getOcupados(),
            p.getPuerta()
        };
        modelo.addRow(fila);
    }

    tablaVuelos.setModel(modelo);
} 
}
