/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.airpot.airport.t1poo.UI;
import com.airpot.airport.t1poo.entidades.TarjetaEmbarque;
import com.airpot.airport.t1poo.gestion.TarjetaEmbqGestionDAO;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andro
 */
public class MantenimientoTarjEmbq extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoTarjEmbq.class.getName());
    
    //Creamos el objeto TarjetaEmbqGestionDAO para el acceso a metodos
    private TarjetaEmbqGestionDAO trjDao = new TarjetaEmbqGestionDAO();
    
    //para recordar el id original del editado
    private int idOriginal;
    /**
     * Creates new form mantenimientoTarjEmbq
     */
    public MantenimientoTarjEmbq() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cargarTabla();
        //editarBtn.setVisible(false);
        configurarListenerEditarBtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IdTarjEmbqTxt = new javax.swing.JTextField();
        IdPasajeroTxt = new javax.swing.JTextField();
        IdPuertaTxt = new javax.swing.JTextField();
        NroAsientoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarjEmbqTable = new javax.swing.JTable();
        guardarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero Tarjeta Embarque:");

        jLabel2.setText("ID Pasajero:");

        jLabel3.setText("ID Puerta");

        jLabel4.setText("Numero Asiento:");

        IdPuertaTxt.addActionListener(this::IdPuertaTxtActionPerformed);

        tarjEmbqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro. Tarj. Embq", "ID Pasajero", "ID Puerta", "Nro. Asiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tarjEmbqTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarjEmbqTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tarjEmbqTable);

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(this::guardarBtnActionPerformed);

        editarBtn.setText("Editar");
        editarBtn.addActionListener(this::editarBtnActionPerformed);

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(this::eliminarBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(NroAsientoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IdTarjEmbqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IdPuertaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(IdPasajeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IdTarjEmbqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IdPasajeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IdPuertaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NroAsientoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarBtn)
                            .addComponent(editarBtn)
                            .addComponent(eliminarBtn))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        // TODO add your handling code here:
        int idTarjeta = Integer.parseInt(IdTarjEmbqTxt.getText().trim());
        int idPasajero = Integer.parseInt(IdPasajeroTxt.getText().trim());
        int idPuerta = Integer.parseInt(IdPuertaTxt.getText().trim());
        String nroAsiento = NroAsientoTxt.getText().trim();
        trjDao.agregarTarjetaEmbarque(idTarjeta, idPasajero, idPuerta, nroAsiento);
        cargarTabla();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void IdPuertaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPuertaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPuertaTxtActionPerformed

    private void tarjEmbqTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarjEmbqTableMouseClicked
        // TODO add your handling code here:
        /*int fila = tarjEmbqTable.getSelectedRow();
        if(fila!=-1){
            IdTarjEmbqTxt.setText(tarjEmbqTable.getValueAt(fila, 0).toString());
            IdPasajeroTxt.setText(tarjEmbqTable.getValueAt(fila, 1).toString());
            IdPuertaTxt.setText(tarjEmbqTable.getValueAt(fila, 2).toString());
            NroAsientoTxt.setText(tarjEmbqTable.getValueAt(fila, 3).toString());
        }*/
        /*while (tarjEmbqTable.isFocusOwner()){
            editarBtn.setVisible(true);
        }*/
        
        //int fila = tarjEmbqTable.getSelectedRow();
        /*if(fila==-1){
            JOptionPane.showMessageDialog(null,"No ha seleccionado ningun registro de la tabla!", "ERROR AL SELECCIONAR",JOptionPane.WARNING_MESSAGE);
        }
        else if(fila!=-1 && editarBtn.isSelected()){
            System.out.print("Boton seleccionado");
            IdTarjEmbqTxt.setText(tarjEmbqTable.getValueAt(fila, 0).toString());
            IdPasajeroTxt.setText(tarjEmbqTable.getValueAt(fila, 1).toString());
            IdPuertaTxt.setText(tarjEmbqTable.getValueAt(fila, 2).toString());
            NroAsientoTxt.setText(tarjEmbqTable.getValueAt(fila, 3).toString());
        }*/
        
        
    }//GEN-LAST:event_tarjEmbqTableMouseClicked

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        // TODO add your handling code here:
        int fila = tarjEmbqTable.getSelectedRow();
        if(fila!=-1){
            IdTarjEmbqTxt.setText(tarjEmbqTable.getValueAt(fila, 0).toString());
            IdPasajeroTxt.setText(tarjEmbqTable.getValueAt(fila, 1).toString());
            IdPuertaTxt.setText(tarjEmbqTable.getValueAt(fila, 2).toString());
            NroAsientoTxt.setText(tarjEmbqTable.getValueAt(fila, 3).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila!", "ERROR AL SELECCIONAR", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_editarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        // TODO add your handling code here:
        int idTrjEmbq = Integer.parseInt(IdTarjEmbqTxt.getText());
        boolean verificador = trjDao.eliminarRegistroTarjetaEmbq(idTrjEmbq);
        if(verificador) JOptionPane.showMessageDialog(null,"Tarjeta de embarque eliminado","BORRADO EXITOSO",JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(null,"Tarjeta de embarque No eliminado","BORRADO FALLIDO",JOptionPane.ERROR_MESSAGE);
        cargarTabla();
    }//GEN-LAST:event_eliminarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoTarjEmbq().setVisible(true));
    }
    
    private void cargarTabla(){
        DefaultTableModel model = (DefaultTableModel) tarjEmbqTable.getModel();
        model.setRowCount(0); //Limpiar datos
        
        ArrayList<TarjetaEmbarque>tarjEmbqData = trjDao.getData();//Obtenemos los datos de la clase Entity
        
        for(TarjetaEmbarque t : tarjEmbqData){
            model.addRow(new Object[]{
                t.getIdtarjetaEmbarque(),
                t.getIdpasajero(),
                t.getIdpuerta(),
                t.getAsiento()
            });
        }
    }
    
    private void cargarDatosDesdeFila() {
        int fila = tarjEmbqTable.getSelectedRow();
        if (fila == -1) return;

        IdTarjEmbqTxt.setText(tarjEmbqTable.getValueAt(fila, 0).toString());
        IdPasajeroTxt.setText(tarjEmbqTable.getValueAt(fila, 1).toString());
        IdPuertaTxt.setText(tarjEmbqTable.getValueAt(fila, 2).toString());
        NroAsientoTxt.setText(tarjEmbqTable.getValueAt(fila, 3).toString());

        //modoEdicion = true;
        idOriginal = Integer.parseInt(IdTarjEmbqTxt.getText());
    }
    
    private void configurarListenerEditarBtn(){
        //Listener para cambios de seleccion en la tabla:
        tarjEmbqTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                if(!e.getValueIsAdjusting()){
                    actualizarVisibilidadBoton();
                }
            }
            
        });
        
        //Para cuando la tabla pierde el focus:
        tarjEmbqTable.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e){
                //Verificamos si la tabla aun tiene filas seleccionadas
                if(tarjEmbqTable.getSelectedRow()==-1){
                    editarBtn.setVisible(false);
                }
                //Si hay filas seleccionadas entonces que el boton siga siendo visible
            }
            
            @Override
            public void focusGained(FocusEvent e){
                actualizarVisibilidadBoton();
            }
        });
        
        //Listener global para comprobar si el mouse hizo click en otro componente
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseClicked(java.awt.event.MouseEvent event){
                if(!tarjEmbqTable.isFocusOwner()){
                    actualizarVisibilidadBoton();
                }
            }
        });
    }
    
    private void actualizarVisibilidadBoton() {
        boolean tieneSeleccion = tarjEmbqTable.getSelectedRow() != -1;
        boolean tablaTieneFoco = tarjEmbqTable.isFocusOwner();
        
        editarBtn.setVisible(tieneSeleccion && tablaTieneFoco);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdPasajeroTxt;
    private javax.swing.JTextField IdPuertaTxt;
    private javax.swing.JTextField IdTarjEmbqTxt;
    private javax.swing.JTextField NroAsientoTxt;
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tarjEmbqTable;
    // End of variables declaration//GEN-END:variables
}
