/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.airpot.airport.t1poo.UI;

import com.airpot.airport.t1poo.entidades.TarjetaEmbarque;
import com.airpot.airport.t1poo.gestion.TarjetaEmbqGestionDAO;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andro
 */
public class MantenimientoTarjEmbq extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoTarjEmbq.class.getName());

    //Creamos el objeto TarjetaEmbqGestionDAO para el acceso a metodos
    private TarjetaEmbqGestionDAO trjDao = new TarjetaEmbqGestionDAO();

    //para recordar el id original del editado
    private int idOriginal;

    /**
     * Creates new form mantenimientoTarjEmbq
     */
    public MantenimientoTarjEmbq() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cargarTabla();
        configurarListenerEditarBtn();
        IdTarjEmbqTxt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IdTarjEmbqTxt = new javax.swing.JTextField();
        IdPasajeroTxt = new javax.swing.JTextField();
        IdPuertaTxt = new javax.swing.JTextField();
        NroAsientoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarjEmbqTable = new javax.swing.JTable();
        guardarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero Tarjeta Embarque:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 36, -1, -1));

        jLabel2.setText("ID Pasajero:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 80, -1, -1));

        jLabel3.setText("ID Puerta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 124, -1, -1));

        jLabel4.setText("Numero Asiento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 168, -1, -1));
        jPanel1.add(IdTarjEmbqTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 182, -1));
        jPanel1.add(IdPasajeroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 75, 250, -1));

        IdPuertaTxt.addActionListener(this::IdPuertaTxtActionPerformed);
        jPanel1.add(IdPuertaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 250, -1));
        jPanel1.add(NroAsientoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 230, -1));

        tarjEmbqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro. Tarj. Embq", "ID Pasajero", "ID Puerta", "Nro. Asiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tarjEmbqTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarjEmbqTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tarjEmbqTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 6, 452, 275));

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(this::guardarBtnActionPerformed);
        jPanel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 207, -1, -1));

        editarBtn.setText("Editar");
        editarBtn.addActionListener(this::editarBtnActionPerformed);
        jPanel1.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 207, -1, -1));

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(this::eliminarBtnActionPerformed);
        jPanel1.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 207, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        pack();
    }// </editor-fold>                        

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:

        if (!validarCuadrosTxt()) {
            //Vamos a saber si es un registro nuevo o un update
            //int idTarjeta = Integer.parseInt(IdTarjEmbqTxt.getText().trim());
            int idPasajero = Integer.parseInt(IdPasajeroTxt.getText().trim());
            int idPuerta = Integer.parseInt(IdPuertaTxt.getText().trim());
            String nroAsiento = NroAsientoTxt.getText().trim();
            
            if(IdTarjEmbqTxt.getText().isEmpty()){
                //int idTarjeta = Integer.parseInt(IdTarjEmbqTxt.getText().trim());
                trjDao.insertData(idPasajero,nroAsiento,idPuerta);
            }else{
                int idTarjeta = Integer.parseInt(IdTarjEmbqTxt.getText().trim());
                if (!verificarExistenciaIdTarjetaEmbarque(idTarjeta)) {
                    trjDao.insertData(idPasajero, nroAsiento, idPuerta);
                } else {
                    JOptionPane.showMessageDialog(null, "Error: IdTarjeta de Embarque ya esta registrado", "ERROR_REGISTRO", JOptionPane.ERROR_MESSAGE);
                }
            }
            

            

            //trjDao.agregarTarjetaEmbarque(idTarjeta, idPasajero, idPuerta, nroAsiento);
            cargarTabla();
        }

    }                                          

    private void IdPuertaTxtActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void tarjEmbqTableMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:      
    }                                          

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        IdTarjEmbqTxt.setVisible(true);
        int fila = tarjEmbqTable.getSelectedRow();
        if (fila != -1) {
            IdTarjEmbqTxt.setText(tarjEmbqTable.getValueAt(fila, 0).toString());
            IdPasajeroTxt.setText(tarjEmbqTable.getValueAt(fila, 1).toString());
            IdPuertaTxt.setText(tarjEmbqTable.getValueAt(fila, 2).toString());
            NroAsientoTxt.setText(tarjEmbqTable.getValueAt(fila, 3).toString());
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila!", "ERROR AL SELECCIONAR", JOptionPane.WARNING_MESSAGE);
        }

    }                                         

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(!IdTarjEmbqTxt.getText().isEmpty()){
           int idTrjEmbq = Integer.parseInt(IdTarjEmbqTxt.getText());
            trjDao.deleteData(idTrjEmbq);
            cargarTabla(); 
        }
        
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoTarjEmbq().setVisible(true));
    }

    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) tarjEmbqTable.getModel();
        model.setRowCount(0); //Limpiar datos

        ArrayList<TarjetaEmbarque> tarjEmbqData = trjDao.getDatosTarjetaEmbarque();//Obtenemos los datos de la clase Entity

        for (TarjetaEmbarque t : tarjEmbqData) {
            model.addRow(new Object[]{
                t.getIdtarjetaEmbarque(),
                t.getIdpasajero(),
                t.getIdpuerta(),
                t.getAsiento()
            });
        }
    }

    private void cargarDatosDesdeFila() {
        int fila = tarjEmbqTable.getSelectedRow();
        if (fila == -1) {
            return;
        }

        IdTarjEmbqTxt.setText(tarjEmbqTable.getValueAt(fila, 0).toString());
        IdPasajeroTxt.setText(tarjEmbqTable.getValueAt(fila, 1).toString());
        IdPuertaTxt.setText(tarjEmbqTable.getValueAt(fila, 2).toString());
        NroAsientoTxt.setText(tarjEmbqTable.getValueAt(fila, 3).toString());

        //modoEdicion = true;
        idOriginal = Integer.parseInt(IdTarjEmbqTxt.getText());
    }

    private void configurarListenerEditarBtn() {
        //Listener para cambios de seleccion en la tabla:
        tarjEmbqTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                if (!e.getValueIsAdjusting()) {
                    actualizarVisibilidadBoton();
                }
            }

        });

        //Para cuando la tabla pierde el focus:
        tarjEmbqTable.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                //Verificamos si la tabla aun tiene filas seleccionadas
                if (tarjEmbqTable.getSelectedRow() == -1) {
                    editarBtn.setVisible(false);
                }
                //Si hay filas seleccionadas entonces que el boton siga siendo visible
            }

            @Override
            public void focusGained(FocusEvent e) {
                actualizarVisibilidadBoton();
            }
        });

        //Listener global para comprobar si el mouse hizo click en otro componente
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent event) {
                if (!tarjEmbqTable.isFocusOwner()) {
                    actualizarVisibilidadBoton();
                    IdTarjEmbqTxt.setVisible(false);
                    IdTarjEmbqTxt.setText("");
                    IdPasajeroTxt.setText("");
                    IdPuertaTxt.setText("");
                    NroAsientoTxt.setText("");
                }
            }
        });
    }

    private void actualizarVisibilidadBoton() {
        boolean tieneSeleccion = tarjEmbqTable.getSelectedRow() != -1;
        boolean tablaTieneFoco = tarjEmbqTable.isFocusOwner();

        editarBtn.setVisible(tieneSeleccion && tablaTieneFoco);
        //IdTarjEmbqTxt.setVisible(tieneSeleccion && tablaTieneFoco);
    }

    public boolean verificarExistenciaIdTarjetaEmbarque(int idtarjetaEmbarque) {
        ArrayList<TarjetaEmbarque> datos = trjDao.getDatosTarjetaEmbarque();
        for (TarjetaEmbarque t : datos) {
            if (t.getIdtarjetaEmbarque() == idtarjetaEmbarque) {
                return true;
            }
        }
        return false;
    }

    public boolean validarCuadrosTxt() {
        String idTarjeta = IdTarjEmbqTxt.getText().trim();
        String idPasajero = IdPasajeroTxt.getText().trim();
        String idPuerta = IdPuertaTxt.getText().trim();
        String nroAsiento = NroAsientoTxt.getText().trim();
        if (idTarjeta.isEmpty()) {
            System.out.println("idTarjeta esta vacio por lo tanto se esta intentando guardar un registro nuevo");
            //idTarjeta = "0";
            if (!(idPasajero.isEmpty() || idPuerta.isEmpty() || nroAsiento.isEmpty())) {
                if (!(idPasajero.matches("\\d*")
                        || idPuerta.matches("\\d*"))) {
                    System.out.println("Los datos ingresados no son numeros");
                    JOptionPane.showMessageDialog(this, "Error: Los cuadros de texto de: Id tarjeta Embarque, Id pasajero y Id puerta, no pueden tener letras!");
                    return true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: Hay cuadros de texto vacios!", "ERROR_CUADRO_VACIO", JOptionPane.ERROR_MESSAGE);
                return true;
            }
            
            
        }else{
            if (!(idTarjeta.isEmpty() || idPasajero.isEmpty() || idPuerta.isEmpty() || nroAsiento.isEmpty())) {
                if (idTarjeta.matches("\\d*") || idPasajero.matches("\\d*")
                        || idPuerta.matches("\\d*")) {
                    JOptionPane.showMessageDialog(this, "Error: Los cuadros de texto de: Id tarjeta Embarque, Id pasajero y Id puerta, no pueden tener letras!");
                    return true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: Hay cuadros de texto vacios!", "ERROR_CUADRO_VACIO", JOptionPane.ERROR_MESSAGE);
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField IdPasajeroTxt;
    private javax.swing.JTextField IdPuertaTxt;
    private javax.swing.JTextField IdTarjEmbqTxt;
    private javax.swing.JTextField NroAsientoTxt;
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tarjEmbqTable;
    // End of variables declaration                   
}

